# This file may exist some error because of hugging face token (cannot push or commit)
# Please upload such files generated by hugging face by self.

from RepoPipeline import RepoPipeline
from transformers.pipelines import PIPELINE_REGISTRY
from transformers import AutoModel
from transformers import pipeline
from huggingface_hub import Repository

# Registry pipeline
PIPELINE_REGISTRY.register_pipeline(
    "feature-extraction",
    pipeline_class=RepoPipeline,
    pt_model=AutoModel,
    default={"pt": ("Lazyhope/unixcoder-nine-advtest", "main")},
    type="text",
)

pipe = pipeline("feature-extraction", model="Lazyhope/unixcoder-nine-advtest")
repo = Repository("RepoSim4Py", clone_from="Henry65/RepoSim4Py")
pipe.save_pretrained("RepoSim4Py")
repo.push_to_hub()
